name: "SIEM Analyzer"
app_id: "app-siem"
customer_id: "yeti"
version: "0.1.0"
description: "SIEM Analyzer"

schemas:
  path: schemas/schema.graphql

resources:
  path: "resources/*.rs"
  root: /api

auth:
  methods: [jwt, basic]
  signup: auto
  email_signup: true
